[context.deploy-preview]
command = "touch /opt/build/repo/__netlify__/../public/_redirects && echo running node && node __netlify__/redirects.js ctfl_spaceId_PLACEHOLDER GATSBY_CONTENTFUL_ENVIRONMENT_PLACEHOLDER ctfl_accessToken_PLACEHOLDER && yarn build"
