[context.deploy-preview]
command = "mkdir public && pwd && touch public/__redirects && ls -al && echo running node && node __netlify__/redirects.js ctfl_spaceId_PLACEHOLDER GATSBY_CONTENTFUL_ENVIRONMENT_PLACEHOLDER ctfl_accessToken_PLACEHOLDER && yarn build"
