[context.production]
    command = "node __netlify__/redirects.js && gatsby build"

[context.deploy-preview.production]
    command = "node __netlify__/redirects.js && gatsby build"

[context.uat]
    command = "node __netlify__/redirects.js && gatsby build"