[context.production]
    command = "node __netlify__/redirects.js  $(ctfl_spaceId) $(GATSBY_CONTENTFUL_ENVIRONMENT) $(ctfl_accessToken) && gatsby build"

[context.deploy-preview.production]
    command = "node __netlify__/redirects.js $ctfl_spaceId $GATSBY_CONTENTFUL_ENVIRONMENT $ctfl_accessToken && gatsby build"

[context.uat]
    command = "node __netlify__/redirects.js && gatsby build"