# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run lint!
      - run: yarn lint
      # run tests!
      - run: yarn test

  migrate:
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: node ./.circleci/scripts/migrate.js $SPACE_ID "CI_MIGRATION" $MANAGEMENT_API_KEY

  deploy-develop:
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: node ./.circleci/scripts/migrate.js $SPACE_ID "develop" $MANAGEMENT_API_KEY

  deploy-uat:
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: node ./.circleci/scripts/migrate.js $SPACE_ID "UAT" $MANAGEMENT_API_KEY

  deploy-master:
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: node ./.circleci/scripts/migrate.js $SPACE_ID "master" $MANAGEMENT_API_KEY

  deploy-test:
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: node ./.circleci/scripts/migrate.js $SPACE_ID "develop" $MANAGEMENT_API_KEY

workflows:
  version: 2
  build-migrate:
    jobs:
      - migrate:
          filters:
            branches:
              only:
                - test
              ignore:
                - /^feature\/*/
      - build:
          requires:
            - migrate
          filters:
            branches:
              only:
                - test
              ignore:
                - /^feature\/*/
      - approve-deployment:
          type: approval
          requires:
            - migrate
            - build
          filters:
            branches:
              only:
                - master
                - test
                - UAT
      - deploy-develop:
          requires:
            - migrate
            - build
          filters:
            branches:
              only: develop
      - deploy-test:
          requires:
            - approve-deployment
          filters:
            branches:
              only: test
      - deploy-uat:
          requires:
            - approve-deployment
          filters:
            branches:
              only: UAT
      - deploy-master:
          requires:
            - approve-deployment
          filters:
            branches:
              only: master
