# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.14
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run lint!
      - run: yarn lint
      # run tests!
      - run: yarn test

  build:
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - run: node ./.circleci/scripts/migrate.js $SPACE_ID "CI_MIGRATION" $MANAGEMENT_API_KEY
      - run: yarn build

  deploy-develop:
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: node ./.circleci/scripts/migrate.js $SPACE_ID "develop" $MANAGEMENT_API_KEY

  deploy-uat:
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: node ./.circleci/scripts/migrate.js $SPACE_ID "UAT" $MANAGEMENT_API_KEY

  deploy-master:
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: node ./.circleci/scripts/migrate.js $SPACE_ID "master" $MANAGEMENT_API_KEY

  deploy-test:
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: node ./.circleci/scripts/migrate.js $SPACE_ID "develop" $MANAGEMENT_API_KEY

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - approve-deployment:
          type: approval
          requires:
            - test
            - build
          filters:
            branches:
              only:
                - master
                - UAT
      - deploy-develop:
          requires:
            - test
            - build
          filters:
            branches:
              only: develop
